### ISSUE TITLE
Thread 'main' panicking resulting in history file not being properly extracted

### ISSUE THREAD

**Issue by Celestial-Stars** [TCA166/CK3-history-extractor#6] opened 2024-11-12 13:24 UTC
After running through the program the history file is not being properly extracted. Attached is the error that I am getting.

Edit to provide more information:
Tried autosave as well as save made during debug mode. Running 1.13.2 unmodded with all dlc except legends of the dead, courture of the capets, and north african atire.

![Screenshot 2024-11-12 152038](https://github.com/user-attachments/assets/df18d543-6491-4bfb-bcfc-2eac86e8c60b)

**Comment by TCA166** [comment] 2024-11-12 16:47
Thank you for letting me know. Is there a way you could provide the save file you used? Without it there's not much I can gather, but based on the crash information I can tell that your save file contains something extraordinary indeed

**Comment by Celestial-Stars** [comment] 2024-11-13 07:47
https://file.io/iDEJsYe70cuU

here are 3 saves. Crashed save is the one I first shared. I decided to try again with 2 other saves. 

Crashed save was orginally multiplayer but launched again in single player

Sultan tahir is single player game

and autosave 2 is the same as crashed save but without launching it in debug singleplayer afterwards


Note each save seemed to have similar errors but none of them were at the same point
![Screenshot 2024-11-13 083153](https://github.com/user-attachments/assets/f9961cc9-99ff-441a-bcca-c1c3261713df)
![Screenshot 2024-11-13 082858](https://github.com/user-attachments/assets/34364ea6-5576-4a95-b165-b825045e1c8b)

**Comment by Celestial-Stars** [comment] 2024-11-13 07:48
If you need any additional information just ask. I am figuring this out as I go along. Fine to download software that may help with troubleshooting

**Comment by TCA166** [comment] 2024-11-13 09:22
I have managed to replicate your issue, though the progress bar didn't match your screenshot. Weird, probably down to thread shenanigans.  
I also have managed to fix your issue, your two issues actually. One save file you have provided had a declared player have their id equal -1, didn't know that could happen. Probably down to them dropping out right? So that's ```Crashed Save.ck3``` no longer crashing, at least on my machine. ```Sultan_Tahir_of_Persia_958_07_12.ck3``` was crashing because I had forgotten to adjust how I compile the Windows executable. Worrisome because that implies that all the people who have downloaded the Windows executable since like a version ago have had their instances crashing and did nothing about it. Lovely. The autosave is ironman encoded and there's not much I can do about it. I refer you to the readme for instructions on how to deal with it. Anywho thank you for letting me know about the issue, I will try to release a hotfix by the week's end and once you download that the issue should be resolved. If you don't want to wait you can always try compiling the source code yourself.

**Comment by Celestial-Stars** [comment] 2024-11-13 14:27
Thank you so much. I didn't realise it was ironman encoded to be honest didn't check I was just checking a bunch of saves which I had to make sure it wasn't just that one

**Comment by TCA166** [comment] 2024-11-13 22:47
The issue is now fixed in release v.2.3.2

**Closed by TCA166** 2024-11-13 22:47 UTC
